### ISSUE TITLE
Cant download the TRMM data

### ISSUE THREAD

**Issue by shubho17apr** [cvitolo/r_hddtools#11]
I tried downloading the TRMM monthly data using the codes examples in the package,
but it showing the following error..

trying URL 'ftp://disc2.nascom.nasa.gov/data/TRMM/Gridded/3B43_V7/2009/3B43.090101.7.precipitation.accum'
trying URL 'ftp://disc2.nascom.nasa.gov/data/TRMM/Gridded/3B43_V7/2009/3B43.090201.7.precipitation.accum'
The following files are currently not available for download: 

[1] "ftp://disc2.nascom.nasa.gov/data/TRMM/Gridded/3B43_V7/2009/3B43.090101.7.precipitation.accum"
[2] "ftp://disc2.nascom.nasa.gov/data/TRMM/Gridded/3B43_V7/2009/3B43.090201.7.precipitation.accum"
There are no files available, try a different temporal window.
Warning messages:
1: In download.file(url = filesURLs[j], destfile = file.path(td, basename(filesURLs[j])),  :
  InternetOpenUrl failed: 'The login request was denied
'
2: In download.file(url = filesURLs[j], destfile = file.path(td, basename(filesURLs[j])),  :
  InternetOpenUrl failed: 'The login request was denied

**Comment by cvitolo** [comment]
The server that hosts TRMM data requires authentication, therefore the TRMM function has been removed from the current version of the package. Sorry about that!
