### ISSUE TITLE
A problem when trying to download some stations

### ISSUE THREAD

**Issue by matteodefelice** [cvitolo/r_hddtools#14]
I was trying to get `mddPerYear` of all the European stations. I have a problem when trying to download some stations, for example `6502110`. 
If: 
```
tt <- tsGRDC(stationID = '6502110')
Station does not have monthly records
```
And then `tt` is empty, a NULL. But if I download the data from the ftp, i.e. the file `europe.zip` at ftp://ftp.bafg.de/pub/REFERATE/GRDC/ltdata/ that stations is not empty (here the file https://cl.ly/1H2I1Y2l3G06 )
I have tried to find an explanation on the documentation but nothing...can you help me? 
**UPDATE**: looking in the code I can see that the function retrieves only the stations where the `statistics` field is 1, but I still don't understand...

**Comment by cvitolo** [comment]
Hi @matteodefelice ! This issue is now fixed in my latest commit. There was a problem in the function that filters the original data.frame. Well spotted!
