### ISSUE TITLE
did you see that your pkg is archived on CRAN now?

### ISSUE THREAD

**Issue by sckott** [cvitolo/r_hddtools#17]
https://cran.rstudio.com/web/packages/hddtools/

looks like they emailed you and problems weren't fixed in time. Did you need any help with the problems they emailed about?

**Comment by sckott** [comment]
@cvitolo can you please reply, are you getting these notifications?

**Comment by cvitolo** [comment]
Hi @sckott, not sure why I did not get a notification.

I have been trying to fix this problem for a long time but I cannot reproduce the error and I have run out of ideas :(

**Comment by sckott** [comment]
Can you show me what the problem is?

**Comment by cvitolo** [comment]
@sckott thanks a lot for asking!

When I run
`devtools::check(args = c('--as-cran'))`
I get 0 errors, 0 notes, 0 warnings

However [travis](https://api.travis-ci.org/v3/job/366142773/log.txt) complains about 
`Error: Test tsGRDC function (@test-tsGRDC.R#6)`

I don't know how to reproduce the error

**Comment by sckott** [comment]
What was the original problem cran maintainers emailed you about? it'd be good to make sure we address the problem if it still exists.

looks like Travis is passing again. 

In general, I'd recommend: 

- for rests, skip any tests on cran that do HTTP requests. Simply put `skip_on_cran()` (From `testthat`) in the beginning of the `test_that` block
- for examples: wrap any examples that do HTTP requests in `\dontrun{}` - it looks like you're already doing this

Also:

- I'd suggest moving away from `RCurl` to use either the http client i maintain [crul](https://github.com/ropensci/crul/) or [httr](https://github.com/r-lib/httr/), or the low level pkg [curl](https://github.com/jeroen/curl/). The former (`crul`) i maintain so you can get quick fixes and answers if you go that way - and it has webmocking and test caching via some other pkgs I made, so it might be worth trying. `RCurl` is still maintained, but is not as easy to use as alternatives.
- likewise, moving from `XML` to `xml2` would be a good idea - `xml2` is much easier to use in my opinion

**Comment by cvitolo** [comment]
Thanks a lot @sckott! Followed your advices and the package is back on cran now!
