### ISSUE TITLE
TRMM data download from archive servers (DAAC)

### ISSUE THREAD

**Issue by gregor-d** [cvitolo/r_hddtools#18]
Hello,
is there any chance that you will include a function to download TRMM data from the archive-servers (Goddard Distributed Active Archive Center (GES DISC DAAC))?
http://mirador.gsfc.nasa.gov/cgi-bin/mirador/presentNavigation.pl?project=TRMM&tree=project

**Comment by cvitolo** [comment]
Hi! Unfortunately I have no plan to add the above function because the server requires authentication.

**Comment by gregor-d** [comment]
Ok, I see.
I know the MODIS package has authentication implemented so maybe you could use that as well? Anyway, thank you.
