### ISSUE TITLE
news and release notes

### ISSUE THREAD

**Issue by sckott** [cvitolo/r_hddtools#19]
Seems like there's no NEWS on the CRAN page for your package https://cran.r-project.org/web/packages/hddtools/index.html - Remove https://github.com/ropensci/hddtools/blob/master/.Rbuildignore#L12 and then NEWS will show up on the CRAN page, 

also, there's no news for this current CRAN version in your news file. 

and please do git tag each CRAN version and update your release notes associated with that tag

thanks! -S

**Comment by cvitolo** [comment]
Thanks @sckott! I'll do that next week, when back from holiday :)

**Comment by cvitolo** [comment]
This is now done, many thanks @sckott !
