### ISSUE TITLE
tsGRDC function error

### ISSUE THREAD

**Issue by giacfalk** [cvitolo/r_hddtools#21]
Running the following

`m3_Malawi<- tsGRDC(stationID = "1992700",
                 plotOption = TRUE)`

I receive the following error:

`Using cached data.
Station has monthly records
Error in matrix(no_spaces, nrow = rows_to_read, byrow = TRUE) : 
  data is too long`

What does it mean?

**Comment by cvitolo** [comment]
Hi @giacfalk , thanks for reporting this. 
There was a mistake in the message, in reality data are not available at your selected station.

The message is now fixed.

```
m3_Malawi<- tsGRDC(stationID = "1992700", plotOption = TRUE)
Using cached data.
Error in tsGRDC(stationID = "1992700", plotOption = TRUE) : 
  Data are not available at this station
```

**Comment by ecor** [comment]
Hi @cvitolo , the same error message occurs for the stationIDs  put in the function example (see below). Are these stations with no data? Thank you Emanuele @ecor 
 
Adaitu <- tsGRDC(stationID = "1577602")
Using cached data.
Error in tsGRDC(stationID = "1577602") : 
  Data are not available at this station
Adaitu <- tsGRDC(stationID = catalogueGRDC()$grdc_no[1000], plotOption = TRUE)
Using cached data.
Using cached data.
Error in tsGRDC(stationID = catalogueGRDC()$grdc_no[1000], plotOption = TRUE) : 
  Data are not available at this station
