### ISSUE TITLE
tsGRDC error

### ISSUE THREAD

**Issue by esmoreido** [cvitolo/r_hddtools#22]
Dear Claudia, 
please help resolving this issue:
`library(hddtools)

areaBox <- raster::extent(98.5, 105.5, 51.7, 56.5)

GRDC_catalogue_bratsk <- catalogueGRDC(areaBox = areaBox)

bratsk <- tsGRDC(stationID = GRDC_catalogue_bratsk$grdc_no, plotOption = TRUE)`

The code ends with an error:
`Using cached data.

Error in charToRaw(URL) : argument must be a character vector of length 1`

Thanks in advance!

**Comment by cvitolo** [comment]
Hi @esmoreido , thanks for filing this issue. 

There was a change in the file name on the GRDC side that caused this error. This is now fixed.

Please reinstall hddtools from GitHub 

`devtools::install_github("ropensci/hddtools")`

and run the following:

```
library(hddtools)
areaBox <- raster::extent(98.5, 105.5, 51.7, 56.5)
GRDC_catalogue_bratsk <- catalogueGRDC(areaBox = areaBox)
bratsk <- tsGRDC(stationID = GRDC_catalogue_bratsk$grdc_no[1], plotOption = TRUE)
```

Please note that stationID should be a single ID (e.g. the first ID is GRDC_catalogue_bratsk$grdc_no[1])
