### ISSUE TITLE
broken link in hddtools blog post

### ISSUE THREAD

**Issue by stefaniebutland** [cvitolo/r_hddtools#23]
Hi Claudia,

In your rOpenSci [blog post](https://raw.githubusercontent.com/ropensci/roweb2/master/content/blog/2017-03-07-hddtools.md) on hddtools, this link is broken: http://pennine.ddns.me.uk/riverlevels/ConciseList.html and I can't find a replacement. Do you have a new link for it?

**Comment by maelle** [comment]
Friendly ping @cvitolo :slightly_smiling_face:

**Comment by cvitolo** [comment]
Hi @stefaniebutland and @maelle! Thank for pointing me to this broken link. The website is down and that list is no longer available. However we can point to this list:
http://apps.sepa.org.uk/database/riverlevels/SEPA_River_Levels_Web.csv.

I amended the vignette accordingly. Shall I send a PR to amend the blog post?

**Comment by maelle** [comment]
Thanks! I've made a commit and pinged you in it, please tell me whether the new text reads well. Thanks for updating the vignette!

**Comment by cvitolo** [comment]
Thank you @maelle , the text reads well. I added a comment to your commit. Closing this issue now.
