### ISSUE TITLE
tsMOPEX: MOPEX URL is outdated

### ISSUE THREAD

**Issue by tmover** [cvitolo/r_hddtools#24]
tsMOPEX)_ cannot pull data since its URL is outdated.
The data are now at:
https://hydrology.nws.noaa.gov/gcip/mopex/US_Data/
I am able to pull data from this location using the read.fwf call but RCurl::url.exists(theurl) still returns FALSE.

**Comment by cvitolo** [comment]
Hi @tmover, thanks for flagging this problem. I fixed the URL and now data can be retrieved again.
