### ISSUE TITLE
cran archived

### ISSUE THREAD

**Issue by sckott** [cvitolo/r_hddtools#25]
@cvitolo Did you see that it was archived on cran? I imagine so, but jut in case i'm checking in.

**Comment by cvitolo** [comment]
Hi @sckott, thanks for the heads up!
Just fixed the problem and re-submitted.
Hopefully will be on CRAN soon.

**Comment by cvitolo** [comment]
hddtools is back on CRAN (https://cran.r-project.org/web/packages/hddtools/index.html)

**Comment by sckott** [comment]
awesome 🎉
