### ISSUE TITLE
MOPEX connection timed out

### ISSUE THREAD

**Issue by davehah** [cvitolo/r_hddtools#28]
It seems like https://hydrology.nws.noaa.gov/gcip/mopex/US_Data/ is unreachable thus cannot be accessed by hddtools. 

Did the dataset get moved to a new URL or is the access down?

**Comment by maelle** [comment]
For info, we're looking for a new maintainer / a new maintainer team for this package, see #31. If you read this and are a hddtools user, feel free to volunteer, we'd be happy to help.

**Comment by dhugpeter** [comment]
I have just checked and the URL works fine, however the correct URL is: https://hydrology.nws.noaa.gov/pub/gcip/mopex/US_Data/ [pub] was missing from your URL. 
The `tsMOPEX()` function works as long as the id of the area is correct.
