### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [cvitolo/r_hddtools#31]
Or a new maintainer _team_ :smiley: 

If you're interested, please comment in the issue. 
For more info, see

* [our guidance on _Changing package maintainers_](https://devguide.ropensci.org/changing-maintainers.html);
* [our _Package Curation Policy_](https://devguide.ropensci.org/curationpolicy.html).

**Comment by Athene-ai** [comment]
I am interested

**Comment by dhugpeter** [comment]
Hi @maelle 
I work in hydrology and I would be interested to invest some time. One aim would be to get it back on CRAN?
Edit: and replacing the rgdal and sp dependencies.

**Comment by maelle** [comment]
Thank you @dhugpeter!

 I'll send you an invite to the GitHub organization with access to this repo (you'll need to have enabled two-factor authentication see https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication) and to our slack workspace that has a package-maintennace channel.

**Comment by maelle** [comment]
Regarding your precise questions
- Getting it back on CRAN would be nice, but you don't have to.
- Your comment on dependencies sounds right indeed!
We'll be happy to help!

**Comment by maelle** [comment]
Closing for clarity :-)
