### ISSUE TITLE
Error in graphics::par(old.par)

### ISSUE THREAD

**Issue by cvitolo** [cvitolo/r_hddtools#4]
This issue is part of this [ropensci review](https://github.com/ropensci/onboarding/issues/73)

@ledell said:

Found a possible bug:
library(raster)
Loading required package: sp
b <- brick('trmm_acc.tif')
plot(b)
Error in graphics::par(old.par) :
invalid value specified for graphical parameter "pin"

**Comment by cvitolo** [comment]
@ledell I cannot reproduce your error here.

Have you generated the file trmm_acc.tiff using the `TRMM()` function before running the `brick()` command?  

@mdsumner suggested to change slightly the workflow for the TRMM function. 
Please install the latest version of hddtools from github and test the TRMM function using the example code below. Please let me know if the problem persists, thanks!

```
# Define a bounding box
areaBox <- raster::extent(-10, 5, 48, 62)
# Define a temporal extent
twindow <- seq(as.Date("2012-01-01"), as.Date("2012-03-31"), by = "months")
# Retreive mean monthly precipitations from 3B43_V7 (based on a bounding box and time extent)
TRMMfile <- TRMM(twindow = twindow, areaBox = areaBox)
library(raster)
plot(TRMMfile)
```

**Comment by mdsumner** [comment]
Seems fine now, here on Windows.

**Comment by cvitolo** [comment]
@mdsumner  many thanks! 

@ledell is this working for you too?

**Comment by ledell** [comment]
@cvitolo Yes, this is working on my end (on a mac).

**Comment by cvitolo** [comment]
Great, thanks! I'm closing this now :)
